USE master
GO
CREATE DATABASE OrignalDB ON PRIMARY  
( NAME = N'OrignalDB' ,               -- 파일의 논리적 이름
  FILENAME = N'C:\01_SQL_DATA\SNAPT.mdf' 
)
LOG ON
( NAME = N'OrignalDB_log' ,               -- 파일의 논리적 이름
  FILENAME = N'C:\02_SQL_BACKUP\SNAPT_log.mdf' 
)
GO

USE OrignalDB
GO
CREATE TABLE SNAPT(
  col1 int identity,
  col2 int)
GO
INSERT INTO SNAPT VALUES (10)
INSERT INTO SNAPT VALUES (20)
INSERT INTO SNAPT VALUES (30)
GO

SELECT * FROM SNAPT

INSERT INTO SNAPT VALUES (40)
INSERT INTO SNAPT VALUES (50)
INSERT INTO SNAPT VALUES (60)
GO

INSERT INTO SNAPT VALUES (70)
INSERT INTO SNAPT VALUES (80)
INSERT INTO SNAPT VALUES (90)
GO

INSERT INTO SNAPT VALUES (100)
INSERT INTO SNAPT VALUES (110)
INSERT INTO SNAPT VALUES (120)
GO

INSERT INTO SNAPT VALUES (130)
INSERT INTO SNAPT VALUES (140)
INSERT INTO SNAPT VALUES (150)
GO

SELECT * FROM SNAPT


USE master
ALTER DATABASE OrignalDB SET OFFLINE 

ALTER DATABASE OrignalDB SET ONLINE

 BACKUP LOG OrignalDB TO DISK=
'C:\03_SQL_TEMP_BACKUP\TEMPBACKUP.BAK'
	WITH NO_TRUNCATE, INIT  