SELECT *
FROM DEPARTMENT;
SELECT *
FROM EMPLOYEE;

CREATE TABLE DEPARTMENT_TEST2
(	DEPTNO INT NOT NULL, 
	DEPTNAME CHAR(10), 
	FLOOR INT DEFAULT 9,
	PRIMARY KEY(DEPTNO)
	);

SELECT *
FROM DEPARTMENT_TEST2;

INSERT INTO DEPARTMENT_TEST2 VALUES(1, '영업', 8);
INSERT INTO DEPARTMENT_TEST2 VALUES(2, '기획', 10);
INSERT INTO DEPARTMENT_TEST2 VALUES(3, '개발', 9);
INSERT INTO DEPARTMENT_TEST2 VALUES(4, '총무', 7);
INSERT INTO DEPARTMENT_TEST2 VALUES(5, '홍보', '');
INSERT INTO DEPARTMENT_TEST2 VALUES(5, '', '');   -- 오류 PRIMARY KEY 제약조건 
INSERT INTO DEPARTMENT_TEST2 VALUES(6, '', '');
INSERT INTO DEPARTMENT_TEST2 VALUES('', '', '');

